export let data_participants = [{name:"Louis Maurice ", times:1},
								{name:"Jeanne Lemasson", times:1},
								{name:"Edgar Couppé", times:1},
								{name:"Manon Laurent", times:3},
								{name:"Luna Piaraly", times:6},
								{name:"Sarah Liabes", times:3},
								{name:"Charlotte-Alicia Bouée", times:1},
								{name:"Charlotte-Alicia Bouée", times:5},
								{name:"Ghislaine Diguoug", times:1},
								{name:"Ghislaine Diguoug", times:5},
								{name:"Etienne Pellissier", times:10},
								{name:"Sarah Daher", times:5},
								{name:"Laury Kibamba", times:10},
								{name:"Laury Kibamba", times:10},
								{name:"Quentin Negrel", times:1},
								{name:"Clément Bourles", times:10},
								{name:"Chloé Leyssens", times:2},
								{name:"Mehdi El Kouarati", times:2},
								{name:"Tom Forté", times:1},
								{name:"Sacha Abitbol", times:11},
								{name:"Redha Moulkaf", times:1},
								{name:"Redha Moulkaf", times:3},
								{name:"Pierre Monroux", times:11},
								{name:"Gwendal Grison", times:6},
								{name:"Vansh Nath", times:3},
								{name:"Jules Lefèvre", times:1},
								{name:"Pacôme Fromager", times:3},
								{name:"Antoine Heitzmann", times:6},
								{name:"Rémy Fayet", times:1},
								{name:"Edson Fernandes Maciel", times:3},
								{name:"Antoine  Bergier ", times:1},
								{name:"Edwin Feneux", times:1},
								{name:"Thomas Vujasinovic", times:3},
								{name:"Cléa Leandri", times:3},
								{name:"Simon Bastide", times:3},
								{name:"Lauren Calvosa", times:1},
								{name:"Etienne Pellissier", times:1},
								{name:"Eliott Dionnet", times:3},
								{name:"Arthur Evain", times:3},
								{name:"Thomas Campagne", times:1},
								{name:"Margot Mottais", times:1},
								{name:"Axel Guimbault", times:3},
								{name:"Fanny Bui", times:1},
								{name:"Gwendal Deleage", times:3},
								{name:"Mathieu Oriol", times:11},
								{name:"Paul Archer", times:3},
								{name:"Rahma Loukil", times:1},
								{name:"Pierre Reboul Salze", times:1},
								{name:"Timothée Rattez", times:6},
								{name:"Manon Strasser", times:11},
								{name:"Octave Jagora", times:1},
								{name:"Laury Kibamba", times:11},
								{name:"Camil Chabbouh", times:3},
								{name:"Eya Mami", times:1},
								{name:"Joel Cabrera", times:3},
								{name:"Quentin Negrel", times:1},
								{name:"Quentin Revillon", times:11},
								{name:"Anissa El Idrissi- Feissel", times:3},
								{name:"Frédéric Srichanwit", times:1},
								{name:"Adrien Roy", times:11},
								{name:"Camelia Rekioua", times:1},
								{name:"Antoine Fauve", times:1},
								{name:"Valentin Povse", times:6},
								{name:"Elie Bosle", times:3},
								{name:"Raphaël Carré", times:11},
								{name:"Jesús Sebastián Lamas", times:6},
								{name:"Hamza Arji", times:3},
								{name:"Léo Ribierre", times:6},
								{name:"Manuel David Maya Rosero", times:3},
								{name:"Ariane Petit", times:3},
								{name:"Liliána Sulyok", times:3},
								{name:"Marc Justo Arbona", times:3},
								{name:"Marc Hébert", times:1},
								{name:"David Muy", times:6},
								{name:"Antonin Granados", times:6},
								{name:"Thibaud Chasteauneuf", times:1},
								{name:"Ikrame Amallah", times:3},
								{name:"Antoine Besson", times:0},
								{name:"Maxime Saffon", times:1},
								{name:"Julia Tevissen", times:3},
								{name:"Camille Séguineau De Préval", times:3},
								{name:"Yahya Moustahsane", times:6},
								{name:"Alexander Hare", times:3},
								{name:"Tom Effernelli", times:3},
								{name:"Sylvia Ren", times:1},
								{name:"Baptiste Girardin", times:3},
								{name:"Mathias Anseaume", times:6},
								{name:"Enguerrand Le Niliot", times:3},
								{name:"Chahinez Abbas", times:1},
								{name:"Ghanem Magroune", times:11},
								{name:"Prisha Chandiramani", times:11},
								{name:"Thomas Revol", times:3},
								{name:"Benjamin Ternot", times:1},
								{name:"Théo Renaudo", times:3},
								{name:"Kenzo Cao Van", times:1},
								{name:"Adrien Bertrand", times:1},
								{name:"Khalil Jerbi", times:3},
								{name:"Sébastien Rivière", times:1},
								{name:"Milan Simeon", times:6},
								{name:"Marc Fuschino", times:1},
								{name:"Sacha Radovanovic", times:1},
								{name:"Guillaume Rogron", times:3},
								{name:"Ismail El Ajraoui", times:3},
								{name:"Mathieu Bouteiller", times:1},
								{name:"Louis Bellet", times:1},
								{name:"Maël Messin", times:1},
								{name:"Soline Carle", times:1},
								{name:"Thomas Cadegros", times:1},
								{name:"Quentin Beziau", times:3},
								{name:"Baptiste Drouillet", times:1},
								{name:"Vincent Hekimian", times:1},
								{name:"Yanis Grigy", times:1},
								{name:"Quentin Duplouy", times:3},
								{name:"Blaise Huber", times:1},
								{name:"Mathilde Viellard", times:3},
								{name:"Antoine Huther", times:1},
								{name:"Alexis Baylet", times:1},
								{name:"Sacha Ryszfeld", times:6},
								{name:"Flavie Louis-Ernest", times:1},
								{name:"Ghislaine Diguoug", times:3},
								{name:"Raphael Legrand", times:1},
								{name:"Alessandro Malaguzzi Valeri", times:1},
								{name:"Charlotte Poupat", times:1},
								{name:"Mao Pereira", times:1},
								{name:"Félicité Yvert", times:1},
								{name:"Lucas Michel", times:1},
								{name:"Adam Fayret-Hochart", times:1},
								{name:"Louise Baril", times:11},
								{name:"Jules De Rolland-Alexandre", times:1},
								{name:"Gaspard Vibert", times:1},
								{name:"Lylia Mesa", times:1},
								{name:"Maelys Viegas", times:1},
								{name:"Héloïse Gouarné", times:1},
								{name:"Laura Kubler", times:11},
								];